version: '3.8'

services:
  db:
    image: postgres:14
    container_name: crud_postgres
    restart: always
    environment:
      POSTGRES_USER: rdgr777
      POSTGRES_PASSWORD: 995647
      POSTGRES_DB: crud_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: nest_crud_api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: rdgr777
      DB_PASSWORD: 995647
      DB_DATABASE: crud_db

volumes:
  pgdata: