### Criar UF
POST http://localhost:3000/uf
Content-Type: application/json

{
  "nome": "São Paulo",
  "sigla": "SP"
}

### Criar Cidade (uf id: 1)
POST http://localhost:3000/cidade
Content-Type: application/json

{
  "nome": "Campinas",
  "uf": {
    "id": 1
  }
}

### Criar Estudante (cidade id: 1)
POST http://localhost:3000/estudante
Content-Type: application/json

{
  "nome": "Maria Oliveira",
  "matricula": "20240001",
  "email": "maria.oliveira@example.com",
  "dt_nascimento": "2002-05-12",
  "cidade": {
    "id": 1
  }
}

### Listar UFs
GET http://localhost:3000/uf

### Listar Cidades
GET http://localhost:3000/cidade

### Listar Estudantes
GET http://localhost:3000/estudante

### Ver um estudante
GET http://localhost:3000/estudante/2

### Atualizar UF
PATCH http://localhost:3000/uf/1
Content-Type: application/json

{
  "nome": "São Paulo Atualizado"
}

### Deletar Estudante
DELETE http://localhost:3000/estudante/1